# Not until there are better Github permissions.
# Travis CI wants to "Update your public repositories (Commits, Issues, etc)".
#
# :(

# language: ruby
# rvm:
#   - ruby-head
#   - 2.0.0
#   - 1.9.3
#   - 1.9.2
#   - 1.9.1
#   - 1.8.7
#   - jruby-head
#   - jruby-19mode
#   - jruby-18mode
#   - rbx-19mode
#   - rbx-18mode
#   - ree
